import {Block} from "../assets/common.tsx";

export function Page() {
  return (
      <>
          <Block>
              <p className={`text-1xl`}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Gravida arcu ac tortor dignissim convallis aenean et. Pellentesque elit ullamcorper dignissim cras tincidunt. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Arcu dui vivamus arcu felis bibendum ut tristique et egestas. Nisl vel pretium lectus quam id leo. Aliquet porttitor lacus luctus accumsan tortor. Interdum consectetur libero id faucibus nisl. Arcu dui vivamus arcu felis bibendum ut. Nulla porttitor massa id neque aliquam vestibulum. Ut eu sem integer vitae justo eget magna fermentum iaculis. Tempor orci dapibus ultrices in iaculis nunc. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Purus non enim praesent elementum facilisis leo. Ut eu sem integer vitae justo. Est ultricies integer quis auctor elit sed vulputate mi sit. Diam quis enim lobortis scelerisque fermentum dui. Orci sagittis eu volutpat odio facilisis mauris sit amet.

                  Tincidunt eget nullam non nisi est sit amet facilisis magna. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Vel pretium lectus quam id leo in vitae. Elementum integer enim neque volutpat ac. Turpis in eu mi bibendum neque egestas congue. Pellentesque nec nam aliquam sem. Arcu non odio euismod lacinia at. Diam quis enim lobortis scelerisque fermentum dui faucibus. Commodo ullamcorper a lacus vestibulum sed arcu. Malesuada fames ac turpis egestas. Cursus risus at ultrices mi tempus. Tortor posuere ac ut consequat. Nam libero justo laoreet sit amet cursus sit amet dictum. At tellus at urna condimentum mattis pellentesque id nibh.

                  Suspendisse faucibus interdum posuere lorem. Venenatis urna cursus eget nunc scelerisque viverra mauris. Consectetur adipiscing elit duis tristique sollicitudin nibh sit. Felis eget nunc lobortis mattis aliquam faucibus. Facilisis gravida neque convallis a. Ipsum dolor sit amet consectetur. Quis risus sed vulputate odio ut enim. Dolor magna eget est lorem ipsum dolor sit. Pharetra massa massa ultricies mi. Facilisis sed odio morbi quis commodo odio aenean. Convallis convallis tellus id interdum velit laoreet id.

                  Malesuada nunc vel risus commodo viverra. Quisque egestas diam in arcu cursus euismod. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Nec dui nunc mattis enim ut. Sed elementum tempus egestas sed sed risus. Non odio euismod lacinia at quis. Ornare lectus sit amet est. Nibh nisl condimentum id venenatis. Interdum consectetur libero id faucibus nisl tincidunt eget. Tortor vitae purus faucibus ornare suspendisse sed.

                  Lectus magna fringilla urna porttitor rhoncus. Amet facilisis magna etiam tempor orci eu lobortis elementum nibh. Orci eu lobortis elementum nibh tellus molestie. Feugiat in ante metus dictum at. Eget est lorem ipsum dolor sit. Lorem ipsum dolor sit amet consectetur adipiscing elit. A diam maecenas sed enim. Urna porttitor rhoncus dolor purus non enim. Nunc aliquet bibendum enim facilisis gravida neque convallis. Risus sed vulputate odio ut enim blandit. Eget nullam non nisi est sit amet facilisis.

                  Felis imperdiet proin fermentum leo vel. Elit pellentesque habitant morbi tristique senectus et netus et malesuada. Felis eget velit aliquet sagittis id consectetur purus. At ultrices mi tempus imperdiet nulla malesuada. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Feugiat sed lectus vestibulum mattis. Massa id neque aliquam vestibulum morbi blandit cursus risus. In egestas erat imperdiet sed euismod nisi porta. Eget egestas purus viverra accumsan in nisl. Tristique senectus et netus et malesuada fames ac turpis egestas. Lacus viverra vitae congue eu consequat ac felis donec et. Eget magna fermentum iaculis eu non diam phasellus vestibulum lorem. Eget sit amet tellus cras adipiscing enim. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. A cras semper auctor neque vitae tempus quam pellentesque. Id semper risus in hendrerit gravida rutrum. Nunc non blandit massa enim nec. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.

                  Suscipit adipiscing bibendum est ultricies. Quam elementum pulvinar etiam non. Vitae justo eget magna fermentum iaculis eu. Mauris in aliquam sem fringilla ut morbi. Venenatis a condimentum vitae sapien. Cras semper auctor neque vitae tempus quam pellentesque nec nam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Dictum non consectetur a erat nam at. Blandit aliquam etiam erat velit scelerisque in. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Orci eu lobortis elementum nibh. Enim tortor at auctor urna nunc id cursus metus aliquam. Tellus rutrum tellus pellentesque eu tincidunt. Porttitor rhoncus dolor purus non enim praesent elementum. Erat nam at lectus urna duis. A lacus vestibulum sed arcu non odio euismod lacinia. Sed vulputate mi sit amet mauris commodo. Sapien faucibus et molestie ac.

                  Justo laoreet sit amet cursus sit. Pharetra et ultrices neque ornare aenean euismod elementum. Posuere lorem ipsum dolor sit amet. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Lectus mauris ultrices eros in cursus. Egestas purus viverra accumsan in nisl nisi scelerisque eu. Mattis rhoncus urna neque viverra justo nec ultrices dui sapien. Libero volutpat sed cras ornare arcu dui vivamus. Integer enim neque volutpat ac. Mollis aliquam ut porttitor leo a diam. Ligula ullamcorper malesuada proin libero nunc. In tellus integer feugiat scelerisque varius morbi enim nunc. Semper eget duis at tellus at urna condimentum mattis. Sit amet aliquam id diam maecenas.

                  Neque volutpat ac tincidunt vitae semper quis lectus. At tellus at urna condimentum mattis pellentesque id. Tempus quam pellentesque nec nam aliquam sem et. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. Gravida rutrum quisque non tellus. Massa tincidunt dui ut ornare lectus sit amet. Lacus luctus accumsan tortor posuere ac ut. Nisi vitae suscipit tellus mauris. Vitae ultricies leo integer malesuada nunc vel risus commodo. Eu scelerisque felis imperdiet proin fermentum leo vel orci porta. Mollis nunc sed id semper risus. Pulvinar mattis nunc sed blandit libero volutpat sed cras. Sem fringilla ut morbi tincidunt. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra.

                  Vitae justo eget magna fermentum iaculis eu non. Vitae et leo duis ut diam. Nulla pharetra diam sit amet. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Nunc sed augue lacus viverra vitae congue eu consequat ac. Lobortis feugiat vivamus at augue. Mi bibendum neque egestas congue quisque egestas diam. Dui ut ornare lectus sit amet est placerat. In pellentesque massa placerat duis ultricies lacus sed turpis. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. Tellus cras adipiscing enim eu. Mi proin sed libero enim sed faucibus. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Tincidunt lobortis feugiat vivamus at. Risus quis varius quam quisque id. Ut ornare lectus sit amet est placerat. Justo nec ultrices dui sapien eget. Pulvinar elementum integer enim neque. Et malesuada fames ac turpis egestas integer eget aliquet.
              </p>
          </Block>
      </>
  )
}

